version: '3'

services:
   api:
     build: ./api
     volumes:
       - ./api:/usr/src/app
     ports:
      - 5000:5000
   client:
      build: ./web
      volumes:
        - ./web:/app
      ports:
        - 3000:3000